export const assetManifest = {
  maps: {
    industrial: '/assets/maps/office-s-map.png',
  },
  towers: {
    machineGun: '/assets/towers/machine-gun-sheet.png',
    coffee: '/assets/towers/coffee_tower_sheet.png',
    frost: '/assets/towers/fan_slow_icon.png',
    bomb: '/assets/towers/bomb-tower.png',
    tesla: '/assets/towers/tesla-tower.png',
    microwaveIcon: '/assets/towers/microwave_tower_icon.png',
    wifiIcon: '/assets/towers/wifi_tower_icon.png',
    coffeeIcon: '/assets/towers/coffee_tower_icon.png',
    base: '/assets/towers/tower_base.png',
    weapon: '/assets/towers/tower_weapon.png',
    muzzleFlash: '/assets/towers/muzzle_flash.png',
    bullet: '/assets/towers/bullet.png',
    hitEffect: '/assets/towers/hit_effect.png',
    machineGunTapeBase: '/assets/towers/machinegun_tape_base.png',
    machineGunTapeWeapon: '/assets/towers/machinegun_tape_weapon.png',
    machineGunTapeMuzzleFlash: '/assets/towers/machinegun_tape_muzzle_flash.png',
    machineGunTapeBullet: '/assets/towers/machinegun_tape_bullet.png',
    machineGunTapeHitEffect: '/assets/towers/machinegun_tape_hit_effect.png',
    machineGunTapeIcon: '/assets/towers/machinegun_tape_icon.png',
    machineGunTapeLevel1: '/assets/towers/machinegun_tape_level_1.png',
    machineGunTapeLevel2: '/assets/towers/machinegun_tape_level_2.png',
    machineGunTapeLevel3: '/assets/towers/machinegun_tape_level_3.png',
    coffeeTowerSheet: '/assets/towers/coffee_tower_sheet.png',
    coffeeTowerBase: '/assets/towers/coffee_tower_base.png',
    coffeeTowerWeapon: '/assets/towers/coffee_tower_weapon.png',
    coffeeTowerMuzzleFlash: '/assets/towers/coffee_tower_muzzle_flash.png',
    coffeeTowerBullet: '/assets/towers/coffee_tower_bullet.png',
    coffeeTowerHitEffect: '/assets/towers/coffee_tower_hit_effect.png',
    coffeeTowerIcon: '/assets/towers/coffee_tower_icon.png',
    coffeeTowerLevel1: '/assets/towers/coffee_tower_level_1.png',
    coffeeTowerLevel2: '/assets/towers/coffee_tower_level_2.png',
    coffeeTowerLevel3: '/assets/towers/coffee_tower_level_3.png',
    fanSlowBase: '/assets/towers/fan_slow_base.png',
    fanSlowWeapon: '/assets/towers/fan_slow_weapon.png',
    fanSlowMuzzleFlash: '/assets/towers/fan_slow_muzzle_flash.png',
    fanSlowBullet: '/assets/towers/fan_slow_bullet.png',
    fanSlowHitEffect: '/assets/towers/fan_slow_hit_effect.png',
    fanSlowIcon: '/assets/towers/fan_slow_icon.png',
    fanSlowLevel1: '/assets/towers/fan_slow_level_1.png',
    fanSlowLevel2: '/assets/towers/fan_slow_level_2.png',
    fanSlowLevel3: '/assets/towers/fan_slow_level_3.png',
    microwaveTowerLevel1: '/assets/towers/microwave_tower_level_1.png',
    microwaveTowerLevel2: '/assets/towers/microwave_tower_level_2.png',
    microwaveTowerLevel3: '/assets/towers/microwave_tower_level_3.png',
    wifiTowerLevel1: '/assets/towers/wifi_tower_level_1.png',
    wifiTowerLevel2: '/assets/towers/wifi_tower_level_2.png',
    wifiTowerLevel3: '/assets/towers/wifi_tower_level_3.png',
  },
  enemies: {
    yellow: '/assets/enemies/xiaohuangguai.png',
    yellowRun: '/assets/enemies/yellow-monster-run-sheet.png',
    yellowHit: '/assets/enemies/yellow-monster-hit-sheet.png',
    yellowDeath: '/assets/enemies/yellow-monster-death-sheet.png',
    slacker: '/assets/enemies/slacker-monster.png',
    slackerRun: '/assets/enemies/slacker-monster-run-sheet.png',
    slackerHit: '/assets/enemies/slacker-monster-hit-sheet.png',
    slackerDeath: '/assets/enemies/slacker-monster-death-sheet.png',
    overtime: '/assets/enemies/overtime.png',
    requirement: '/assets/enemies/file-monster.png',
    boss: '/assets/enemies/boss.png',
  },
  effects: {
    explosion: '/assets/effects/explosion-sheet.png',
    muzzle: '/assets/effects/muzzle-flash.png',
    microwaveExplosion: '/assets/effects/microwave_explosion_sheet.png',
    wifiElectricArc: '/assets/effects/wifi_electric_arc_sheet.png',
    coffeeSpraySteam: '/assets/effects/coffee_spray_steam_sheet.png',
  },
  ui: {
    button: '/assets/ui/button.png',
  },
} as const;
