export const assetManifest = {
  maps: {
    industrial: '/assets/maps/office-s-map.png',
  },
  towers: {
    machineGun: '/assets/towers/machine-gun-sheet.png',
    coffee: '/assets/towers/coffee-tower-sheet.png',
    frost: '/assets/towers/fan-frost-tower-sheet.png',
    bomb: '/assets/towers/bomb-tower.png',
    tesla: '/assets/towers/tesla-tower.png',
    base: '/assets/towers/tower_base.png',
    weapon: '/assets/towers/tower_weapon.png',
    muzzleFlash: '/assets/towers/muzzle_flash.png',
    bullet: '/assets/towers/bullet.png',
    hitEffect: '/assets/towers/hit_effect.png',
    machineGunTapeBase: '/assets/towers/machinegun_tape_base.png',
    machineGunTapeWeapon: '/assets/towers/machinegun_tape_weapon.png',
    machineGunTapeMuzzleFlash: '/assets/towers/machinegun_tape_muzzle_flash.png',
    machineGunTapeBullet: '/assets/towers/machinegun_tape_bullet.png',
    machineGunTapeHitEffect: '/assets/towers/machinegun_tape_hit_effect.png',
    machineGunTapeIcon: '/assets/towers/machinegun_tape_icon.png',
  },
  enemies: {
    yellow: '/assets/enemies/xiaohuangguai.png',
    yellowRun: '/assets/enemies/yellow-monster-run-sheet.png',
    yellowHit: '/assets/enemies/yellow-monster-hit-sheet.png',
    yellowDeath: '/assets/enemies/yellow-monster-death-sheet.png',
    slacker: '/assets/enemies/slacker-monster.png',
    slackerRun: '/assets/enemies/slacker-monster-run-sheet.png',
    slackerHit: '/assets/enemies/slacker-monster-hit-sheet.png',
    slackerDeath: '/assets/enemies/slacker-monster-death-sheet.png',
    overtime: '/assets/enemies/overtime.png',
    requirement: '/assets/enemies/file-monster.png',
    boss: '/assets/enemies/boss.png',
  },
  effects: {
    explosion: '/assets/effects/explosion-sheet.png',
    muzzle: '/assets/effects/muzzle-flash.png',
  },
  ui: {
    button: '/assets/ui/button.png',
  },
} as const;
